apiVersion: apps/v1
kind: StatefulSet      # < kind of installation (statefulset vs Deployment)
metadata:
  name: nextcloud-db   # < name of the deployment
  namespace: nextcloud # < namespace where to place the statefulset and pods
  labels:
    app: nextcloud     # < label for tagging and reference
spec:
  serviceName: nextcloud-db-service       # < name of the service   (see service yaml part)
  replicas: 1                             # < number of pods to deploy
  selector:
    matchLabels:
      pod-label: nextcloud-db-pod         # < pod-label for tagging and reference
  template:
    metadata:
      labels:
        pod-label: nextcloud-db-pod
    spec:
     terminationGracePeriodSeconds: 1800
     volumes:
      - name: nextcloud-db-storage        
        hostPath:
          path: /WHNAS/k3s-pv/nextcloud-db-pv
          type: "DirectoryOrCreate"
     containers:
      - name: mariadb
        image: linuxserver/mariadb
        imagePullPolicy: Always
        env:                               # < environment variables. See https://hub.docker.com/r/linuxserver/mariadb
        - name: PGID
          value: "1000" # < owner of mount"  
        - name: PUID                       
          value: "1000" # < owner of mount"
        - name: TZ
          value: America/Central          
        - name: MYSQL_DATABASE
          value: nextcloud
        envFrom:
        - secretRef:
            name: nextcloud-db-secret      # < link reference to the created secret
        volumeMounts:
         - name: nextcloud-db-storage      # < the volume mount in the container. Look at the relation volumelabel->pvc->pv
           mountPath: /config              # < mount location in the container
           subPath: mariadb-config         # < mounted subpath in under /config in container 
---
kind: Service
apiVersion: v1
metadata:
  name: nextcloud-db-service           # < service name (see link with statufulset yaml)
  namespace: nextcloud
spec:
  selector:
    pod-label: nextcloud-db-pod        # < reference to the statefulset (connects the service with the statefulset)
  ports:
    - name: mysql
      protocol: TCP
      port: 3306