apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-server-pvc
  namespace: nextcloud
spec:
  volumeName: nextcloud-server-pv
  accessModes:
    - ReadWriteMany       # < One pod can write to storage. Same value as pv
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti        # < how much data can the pvc claim from pv
