apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  privateKey:
    rotationPolicy: Always
  commonName: weigner-lucky-dogs.duckdns.org
  dnsNames:
  - weigner-lucky-dogs.duckdns.org
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io